server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: tenant-by-domain
          uri: lb://TENANT-SERVICE
          predicates:
            - Path=/api/tenants/**
          filters:
            - RewritePath=/api/tenants/(?<seg>.*), /tenants/${seg}

        - id: tenant-admin
          uri: lb://TENANT-SERVICE
          predicates:
            - Path=/api/admin/tenants,/api/admin/tenants/**
          filters:
            - RewritePath=/api/admin/(?<seg>.*), /admin/${seg}

        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**

        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/api/stock/**

tenant:
  service:
    url: ${TENANT_SERVICE_URL:http://localhost:8083}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/