server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Extrait le sous-domaine : "leroy.localhost:3000" → "leroy"
    set $tenant_id "";
    if ($http_host ~* "^([^.]+)\.") {
        set $tenant_id $1;
    }

    location = /admin.html {
        if ($http_host !~* "^bricoloc\.localhost") {
            return 403;
        }
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    location /api/ {
        proxy_pass http://api-gateway:8080/api/;
        proxy_set_header Host         $host;
        proxy_set_header X-Real-IP    $remote_addr;
        proxy_set_header X-Tenant-Id  $tenant_id;
    }
}